In [1]:
import numpy as np

Why we need Numpy?

In [4]:
import pandas as pd
df = pd.DataFrame(columns=['Age','Score'])

In [5]:
df.head()

Empty DataFrame
Columns: [Age, Score]
Index: []

In [7]:
df['Age'] = np.random.randint(low=0,high=1000000,size=500000)
df['Score'] = np.random.randint(low=0,high=100,size=500000)

In [8]:
df.shape

(500000, 2)

In [10]:
df.head()

Age  Score
0  583902     71
1  633896     29
2  272483     59
3  407539     20
4  823920     10

In [9]:
def grade(score):
    if score>=70:
        return "A"
    elif((score>=50) and (score<70)):
        return 'B'
    elif((score>=35) and (score<50)):
        return 'C'
    else:
        return 'D'

In [12]:
import time
start_for = time.time()
df['Grade']='F'
for i,r in df.iterrows():
    df.at[i,'Grade'] = grade(r.Score)
end_for = time.time()
print("Total Time Taken By ForLoop: ", (end_for - start_for), "Seconds")
df.head()

Total Time Taken By ForLoop:  146.132000207901 Seconds


Age  Score Grade
0  583902     71     A
1  633896     29     D
2  272483     59     B
3  407539     20     D
4  823920     10     D

In [13]:
df.drop(columns=['Grade'],inplace=True)
df.head()

Age  Score
0  583902     71
1  633896     29
2  272483     59
3  407539     20
4  823920     10

In [14]:
start_lambda = time.time()
df['Grade'] = df.apply(lambda r: grade(r.Score), axis=1)
end_lambda = time.time()
print("Total Time Taken By Lambda Function to Execute: ",(end_lambda - start_lambda), "Seconds")

Total Time Taken By Lambda Function to Execute:  33.20799994468689 Seconds


In [15]:
df.drop(columns=['Grade'],inplace=True)
df.head()

Age  Score
0  583902     71
1  633896     29
2  272483     59
3  407539     20
4  823920     10

In [16]:
start_npv = time.time()
df['Grade'] = np.vectorize(grade)(df.Score)
end_npv = time.time()
print("Total Time Taken By Lambda Function to Execute: ",(end_npv - start_npv), "Seconds")

Total Time Taken By Lambda Function to Execute:  0.685999870300293 Seconds


In [17]:
df.head()

Age  Score Grade
0  583902     71     A
1  633896     29     D
2  272483     59     B
3  407539     20     D
4  823920     10     D

In [18]:
#1D
a = np.array([1,2,3,4,5,6,7,8,9,0,-1,-2,-3,-4,-5])

In [19]:
type(a)

numpy.ndarray

In [20]:
#Retrieve elements from 1D
a[0]

1

In [21]:
#Iteration over 1D
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
0
-1
-2
-3
-4
-5


In [22]:
#Slicing on 1D Array
a1 = a[2:7:1]
a1

array([3, 4, 5, 6, 7])

In [23]:
a1 = a[2:7:2]
a1

array([3, 5, 7])

In [24]:
a1 = a[2:7:3]
a1

array([3, 6])

In [26]:
x=[0,5,9]
a2 = a[x]
a2

array([1, 6, 0])

In [27]:
#2D Arrays

In [29]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#fetching elements
a[(1,2)]

6

In [32]:
#iteration
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [33]:
#Slicing on 2D Array
a1 = a[1:3:1, 0:2:1]
a1

array([[4, 5],
       [8, 9]])

Arithmetic Operations on Arrays

In [34]:
a = np.array([1,2,3,4,5])
print(a+2)

[3 4 5 6 7]


In [35]:
print(a-2)

[-1  0  1  2  3]


In [36]:
a = a+10
print(a//3)

[3 4 4 4 5]


In [37]:
print(a**2)

[121 144 169 196 225]


In [38]:
#Arrays to Arrays Operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a*b
c

array([ 5, 12, 21, 32])

Mathematical Operations

In [39]:
c = np.dot(a,b)
c

70

Data Type Conversions

In [45]:
a = np.array([1,0,2,3,4])
a.dtype

dtype('int32')

In [46]:
a = a.astype('int16')

In [47]:
a.dtype

dtype('int16')

In [48]:
a = a.astype('bool')

In [49]:
a

array([ True, False,  True,  True,  True])

In [50]:
a.dtype

dtype('bool')